### ISSUE TITLE
No jupyter notebook found for Image Recommendation Engine

### ISSUE THREAD

**Issue by biranchi2018** [AlexWarembourg/Medium#1]
I read the blog at https://towardsdatascience.com/image-recommendation-engine-leverage-transfert-learning-ec9af32f5239 and arrived to this github repo

https://github.com/AlexWarembourg/Medium/blob/master/product_recommendation.ipynb

But there is not jupyter notebook found

**Comment by AlexWarembourg** [comment]
Hi, Indeed, I will reupload it.
